### ISSUE TITLE
infos

### ISSUE THREAD

**Issue by DVDAndroid** [DVDAndroid/timvision-xposed#1]
@Ric-82
Hey I saw that you had problems with timvision app. Maybe I can help you.
Do you speak Italian?

**Comment by Ric-82** [comment]
Ciao, si sono Italiano :)

Grazie per l'interessamento: dimmi tutto, accetto suggerimenti

**Comment by DVDAndroid** [comment]
ok
nella repository puoi trovare un apk. è un modulo xposed.
non so se funziona al 100%, ma sono riuscito a togliere l'avvertimento del root. (lo so che l'avevi già tolto con rootcloak, per questo disabilitalo prima ;))

fammi sapere

**Comment by Ric-82** [comment]
Ok, ho disabilitato rootcloak, installato e attivato il tuo modulo e ho riavviato. L'avviso che il dispositivo ha il root è scomparso, però continua a non mostrare i contenuti.

Come ho scritto sul forum di RootCloak, qui http://forum.zidoo.tv/index.php?threads/timvision.2052/#post-11747 avanzano l'ipotesi che TimVision controlli anche che il dispositivo abbia permessi user e non root. Sarà per quello che i drm vengono bloccati?

Io non ho idea di come aggirare l'ostacolo

**Comment by DVDAndroid** [comment]
infatti ho scoperto che l'app controlla se è root o meno, e invia dati al server.
ho bloccato questo controllo, ma sembra che non funzioni.

**Comment by DVDAndroid** [comment]
ho aggiornato il modulo.
una volta installato, riavviato, e testato i cambiamenti, allega per favore il log xposed che puoi prendere dall'installer

domani posso controllare meglio il tutto se continua a non funzionare

**Comment by Ric-82** [comment]
Puoi spiegarmi meglio come generare il log, per favore?

**Comment by DVDAndroid** [comment]
apri xposed installer
apri il menu laterale
clicca il tasto salva (dovrebbe salvarlo in memoria interna/xposedinstaller)

poi lo passi sul pc
e lo alleghi qua

**Comment by Ric-82** [comment]
Dovrebbe essere questo, anche se ad occhio non mi sembra contenga molte informazioni

[xposed_error_20161101_225118.txt](https://github.com/DVDAndroid/timvision-xposed/files/565150/xposed_error_20161101_225118.txt)

**Comment by DVDAndroid** [comment]
dal log capisco che il modulo funziona. 
ultima prova e poi ne parliamo domani: prova a cancellare i dati dell'app e ad riaprirla. (se puoi)

**Comment by Ric-82** [comment]
Ci avevo pensato, lo stavo già facendo mentre lo scrivevi ;)

Comunque non cambia nulla...

[xposed_error_20161101_225955.txt](https://github.com/DVDAndroid/timvision-xposed/files/565163/xposed_error_20161101_225955.txt)

Allora ci aggiorniamo nei prossimi giorni, sempre se ne hai voglia. Grazie comunque infinite per l'interessamento

**Comment by DVDAndroid** [comment]
non ho trovato altri modi per bloccare il riconoscimento del root.
l'unico modo sembra togliere il root completamente.

chiudo qui

**Comment by Ric-82** [comment]
Ok, grazie comunque per averci provato.

Se hai le competenze (e mi pare che tu le abbia) a tempo perso potresti provare ad analizzare l'apk di TimVision con questo tool https://ibotpeaches.github.io/Apktool/ magari riesci a capire cosa va a cercare per autorizzare i video drm.

Grazie ancora

**Comment by DVDAndroid** [comment]
Proprio quel tool ho usato. Ho usato anche dex2jar per ottenere le classi java. Il problema che le classi sono offuscate e non è possibile ottenere il codice sorgente.

Dimmi se posso eliminare la repo

**Comment by Ric-82** [comment]
Si certo, liberissimo :)

Pazienza, dovrò installare e disinstallare SuperSU ogni volta, anche se così facendo - visto che avevo dei programmi installati sulla sd con Link2Sd - ho già distrutto una micro sd... :/

Che palle, è assurdo che Netflix non rompa le scatole e TimVision si. Vadano a quel paese.

Grazie sempre per il tentativo
